src/java/au/edu/uts/aip/accounts/AccountController.java
package au.edu.uts.aip.accounts;

import java.sql.*;
import java.util.*;
import java.util.logging.*;
import javax.enterprise.context.*;
import javax.faces.application.*;
import javax.faces.context.*;
import javax.inject.*;
import javax.naming.*;
import javax.servlet.*;
import javax.servlet.http.*;
import javax.sql.*;

/**
 * A backing bean used for account management in our JavaServer Faces application.
 */
@Named
@RequestScoped
public class AccountController {

    // Properties of the Java Bean, used by JSF fields
    private String username;
    private String password;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    /**
     * Get a list of all users in the database.
     * @return a list of all users in the database
     * @throws DataStoreException if there is an error accessing the database
     */
    public ArrayList<AccountDTO> getAllUsers() throws DataStoreException {
        return new AccountDAO().findAll();
    }
    
    /**
     * Attempt to log in using the username/password properties set by JSF.
     * Uses the AccountDAO to perform the password check.
     * @return an outcome corresponding to an insecure welcome page, null if the login failed
     * @throws DataStoreException if there is an error accessing the database
     */
    public String loginDao() throws DataStoreException {
        AccountDAO dao = new AccountDAO();
        AccountDTO user = dao.findUser(username);
        if (password.equals(user.getPassword())) {
            return "/welcome_not_secure?faces-redirect=true";
        } else {
            showError("Incorrect username or password");
            return null;
        }
    }
    
    /**
     * Attempt to log in using the username/password properties set by JSF.
     * Uses the container-managed authentication to perform the password check.
     * @return an outcome corresponding to a secure welcome page, null if the login failed
     */
    public String loginContainer() {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest)context.getExternalContext().getRequest();
        
        try {
          request.login(username, password);
          return "/welcome?faces-redirect=true";
          
        } catch (ServletException e) {
          showError("Incorrect username or password (or you may not have properly configured aipRealm)");
          e.printStackTrace();
          return null;
        }
    }
    
    /**
     * Logs out the current user of the container-managed authentication.
     * @return an outcome corresponding to the login page
     * @throws ServletException if there is no currently logged in user
     */
    public String logoutContainer() throws ServletException {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest)context.getExternalContext().getRequest();
        request.logout();
        return "/login?faces-redirect=true";
    }

    /**
     * Dumps the entire database to the server log.
     * Uses JNDI (i.e., container managed connection pools) to establish a database connection.
     * @throws SQLException if there is an error when communicating with the database
     * @throws NamingException if the JDBC resource "jdbc/aip" can not be found
     */
    public void listUsersJNDI() throws SQLException, NamingException {
        String query = "select username, password, fullname, email, dob " +
                       "from account";
        
        Logger log = Logger.getLogger(this.getClass().getName());
        DataSource ds = InitialContext.doLookup("jdbc/aip");
        
        try (Connection conn = ds.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {

            log.info("The accounts table contains:");
            while (rs.next()) {
                log.info("username = " + rs.getString("username") +
                         ", password = " + rs.getString("password") +
                         ", fullname = " + rs.getString("fullname") +
                         ", email = " + rs.getString("email") +
                         ", dob = " + rs.getDate("dob"));
            }
            log.info("End of accounts table.");
        }
    }
    
    /**
     * Dumps the entire database to the server log.
     * Uses JDBC to establish a database connection directly.
     * <p>
     * Note that this is bad practice! You should always use container-managed connections when working in Java EE.
     * @throws SQLException if there is an error when communicating with the database
     */
    public void listUsersJDBC() throws SQLException {
        String connectionString = "jdbc:derby://localhost:1527/aip";
        String dbUsername = "aip";
        String dbPassword = "aip";
        String query = "select username, password, fullname, email, dob " +
                       "from account";
        
        Logger log = Logger.getLogger(this.getClass().getName());
        
        try (Connection conn = DriverManager.getConnection(connectionString, dbUsername, dbPassword);
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {
            
            log.info("The accounts table contains:");
            while (rs.next()) {
                log.info("username = " + rs.getString(1) +
                         ", password = " + rs.getString(2) +
                         ", fullname = " + rs.getString(3) +
                         ", email = " + rs.getString(4) +
                         ", dob = " + rs.getDate(5));
            }
            log.info("End of accounts table.");
        }
    }
    
    /**
     * Adds a message to the current faces context, so that it will appear in
     * a h:messages element.
     * @param message the text of the error message to show the user
     */
    private void showError(String message) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(message));
    }
}

web/accounts.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Account Administration</title>
    </h:head>
    <h:body>
        <h:messages/>
        <h:dataTable var="row" value="#{accountController.allUsers}">
            <h:column>
                <f:facet name="header">
                    Username
                </f:facet>
                <h:outputText value="#{row.username}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Password
                </f:facet>
                <h:outputText value="#{row.password}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Full Name
                </f:facet>
                <h:outputText value="#{row.fullname}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Email
                </f:facet>
                <h:outputText value="#{row.email}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Date of Birth
                </f:facet>
                <h:outputText value="#{row.dob}"/>
            </h:column>
        </h:dataTable>
        <h:form>
            <p>
                Use a direct JDBC connection:
                <h:commandButton value="List Users to Server Log" action="#{accountController.listUsersJDBC}"/>
            </p>
            <p>
                Use container connection pooling:
                <h:commandButton value="List Users to Server Log" action="#{accountController.listUsersJNDI}"/>
            </p>
        </h:form>
    </h:body>
</html>

web/daologin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>System Login</title>
    </h:head>
    <h:body>
        <h1>Login Form</h1>
        <p>
            This log in form uses a DAO-based login check. It does not use container-managed authentication.
        </p>
        <p>
            You can use the following username/passwords: cbrady/password, mbrady/qwerty, anelson/123456, sfranklin/iloveyou.
        </p>
        <h:form>
            <p>
                <label>Username:
                    <h:inputText value="#{accountController.username}"/>
                </label>
            </p>
            <p>
                <label>Password:
                    <h:inputSecret value="#{accountController.password}"/>
                </label>
            </p>
            <h:messages style="color: red;"/>
            <p>
                <h:commandButton value="Log In" action="#{accountController.loginDao}"/>
            </p>
        </h:form>
    </h:body>
</html>

web/datastore_error.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <p>
            An error occurred when attempting to communicate with the database.
        </p>
        <p>
            Please check your GlassFish settings.
        </p>
        <p>
            You have been redirected to this error page because of the configuration in web.xml:
        </p>
        <pre>
    &lt;error-page>
        &lt;exception-type>au.edu.uts.aip.accounts.DataStoreException&lt;/exception-type>
        &lt;location>/faces/datastore_error.xhtml&lt;/location>
    &lt;/error-page>
        </pre>
        <p>
            The underlying error message was:
            <b><h:outputText value="#{facesContext.externalContext.requestMap['javax.servlet.error.message']}"/></b>
        </p>
    </h:body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Week 5 Tutorials</title>
    </h:head>
    <h:body>
        <h1>Week 5 Tutorials</h1>
        <p>Before running this project, you need to:</p>
        <ul>
            <li>Create a JavaDB database named aip, with username aip and password aip.</li>
            <li>Execute the SQL file named create_db.sql (you can find it using the files tab) on the database named aip.</li>
            <li>Create a JDBC Connection Pool in the GlassFish Server Administration Console.</li>
            <li>Create a JDBC Resource named "jdbc/aip" in the GlassFish Server Administration Console.</li>
            <li>Configure the container managed security realm named aipRealm.</li>
        </ul>
        <p>Full instructions for this configuration can be found in the Week 5 tutorials.</p>
        <p>Please note that it is important to follow the configuration very closely. Typos in the configuration may stop your project from working.</p>
        <p><h:link value="View records in the database" outcome="accounts"/></p>
        <p><h:link value="Log in using DAO" outcome="daologin"/></p>
        <p><h:link value="Log in using container-managed authentication" outcome="login"/></p>
        <p><h:link value="Attempt to access a page that has been secured using container-managed authentication" outcome="welcome"/> (you will be redirected to the login page)</p>
    </h:body>
</html>

web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>System Login</title>
    </h:head>
    <h:body>
        <h1>Login Form</h1>
        <p>
            This log in form uses a container-based login check.
        </p>
        <p>
            You can use the following username/passwords: cbrady2/password, mbrady2/qwerty, anelson2/123456, sfranklin2/iloveyou (note that the usernames are slightly different from the ones I created for the DAO login).
        </p>
        <h:form>
            <p>
                <label>Username:
                    <h:inputText value="#{accountController.username}"/>
                </label>
            </p>
            <p>
                <label>Password:
                    <h:inputSecret value="#{accountController.password}"/>
                </label>
            </p>
            <h:messages style="color: red;"/>
            <p>
                <h:commandButton value="Log In" action="#{accountController.loginContainer}"/>
            </p>
        </h:form>
    </h:body>
</html>

web/secret/another_secure.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>System Login</title>
    </h:head>
    <h:body>
        <p>
            Congratulations, you are successfully logged in!
        </p>
        <p>
            This page <i>is</i> protected by container managed authentication. You should not be able to access it unless you are logged in.
        </p>
        <h:form>
            <p>
                <h:commandButton value="Logout" action="#{accountController.logoutContainer}"/>
            </p>
        </h:form>
    </h:body>
</html>

web/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>System Login</title>
    </h:head>
    <h:body>
        <p>
            Congratulations, you are successfully logged in!
        </p>
        <p>
            This page <i>is</i> protected by container managed authentication. You should not be able to access it unless you are logged in.
        </p>
        <p>
            <h:link value="Visit another secure page" outcome="/secret/another_secure"/>
        </p>
        <h:form>
            <p>
                <h:commandButton value="Logout" action="#{accountController.logoutContainer}"/>
            </p>
        </h:form>
    </h:body>
</html>

web/welcome_not_secure.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>System Login</title>
    </h:head>
    <h:body>
        <p>
            Congratulations, you have successfully logged in!
        </p>
        <p>
            (This particular page, welcome_not_secure.xhtml <i>is not</i> protected by container managed authentication.)
        </p>
    </h:body>
</html>